name: Static Webserver # Name of the Catalog Entry
description: |
  # A Webserver with Rsync attached.
version: # Version of the Catalog to be used
category: # Category to be used for searching catalog entries
maintainer: # The maintainer of the catalog entry
license: # The license
projectURL: # A URL related to the catalog entry
