version: "2"
catalog:
  name: "Concourse"
  version: 0.0.2
  uuid: concourse-airtonix-2
  minimum_rancher_version: v0.51.0
  questions:

    - variable: 'CONCOURSE_DOMAIN'
      default: 'ci'
      label: 'domain which concourse lives on'
      description: 'makes up the FQDN of the concourse ATC as seen by fly clients and remote workers'
      required: true
      type: 'string'

    - variable: 'CONCOURSE_SSH_PORT'
      label: 'external ssh port'
      description: 'For external workers connecting via ssh. make this different from your host ssh port. or find a ssh reverse proxy solution.'
      default: '2222'
      required: true
      type: 'string'

    - variable: 'CONCOURSE_BASICAUTH_ADMIN_USERNAME'
      label: 'admin username'
      default: 'admin'
      required: true
      type: 'string'

    - variable: 'CONCOURSE_BASICAUTH_ADMIN_PASSWORD'
      label: 'admin password'
      default: 'admin'
      required: true
      type: 'password'

    - variable: 'CONCOURSE_DB_USERNAME'
      label: 'database username'
      default: 'concourse'
      required: true
      type: 'string'

    - variable: 'CONCOURSE_DB_PASSWORD'
      label: 'database password'
      default: 'concourse'
      required: true
      type: 'password'

services:
  tsa:
    scale: 1
    health_check:
      port: 8080
      strategy: none
      request_line: GET "/" "HTTP/1.0"
  worker:
    scale: 1
  db:
    scale: 1
