version: "2"

services:

  keys:
    image: airtonix/concourse-certs-generator:0.0.4
    tty: true
    stdin_open: true
    command: cat
    volumes:
      - /mnt/storage/concourse/keys:/concourse-keys

  db:
    hostname: concourse-db
    image: postgres:9.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${CONCOURSE_DB_USERNAME}
      POSTGRES_PASSWORD: ${CONCOURSE_DB_PASSWORD}
      PGDATA: /database
    volumes:
      - /mnt/storage/concourse/db:/database

  tsa:
    image: concourse/concourse
    restart: unless-stopped
    command: web
    ports:
      - "${CONCOURSE_SSH_PORT}:2222"
    expose:
      - 2222
      - 8080
    volumes:
      - /mnt/storage/concourse/keys:/concourse-keys
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: ${CONCOURSE_BASICAUTH_ADMIN_USERNAME}
      CONCOURSE_BASIC_AUTH_PASSWORD: ${CONCOURSE_BASICAUTH_ADMIN_PASSWORD}
      CONCOURSE_EXTERNAL_URL: ${CONCOURSE_SUBDOMAIN}.${CONCOURSE_DOMAIN}
      CONCOURSE_POSTGRES_DATA_SOURCE: postgres://${CONCOURSE_DB_USERNAME}:${CONCOURSE_DB_PASSWORD}@db:5432/concourse?sslmode=disable
      VIRTUAL_HOST: ${CONCOURSE_SUBDOMAIN}
      VIRTUAL_PORT: 8080

  worker:
    image: concourse/concourse
    privileged: true
    restart: unless-stopped
    command: worker
    volumes:
      - /mnt/storage/concourse/keys:/concourse-keys
    environment:
      CONCOURSE_TSA_HOST: tsa
